#!/bin/sh
set -vex

if find /sys/class/drm/card* -type d; then
	devdir=$(find /sys/class/drm/card*/device | tail -n1)
	hmondir=$(find /sys/class/drm/card*/device/hwmon/hwmon* -type d | head -n1)
	echo "162000000" >"$hmondir"/power1_cap
	echo "1" >"$hmondir"/pwm1_enable
	echo "112" >"$hmondir"/pwm1
	echo "s 1 2840" >"$devdir"/pp_od_clk_voltage
	echo "m 1 1200" >"$devdir"/pp_od_clk_voltage
	echo "vo -75" >"$devdir"/pp_od_clk_voltage
	echo "c" >"$devdir"/pp_od_clk_voltage
else
	exit 1
fi
