#!/bin/sh
set -vex

if find /sys/class/drm/card* -type d; then
	devdir=$(find /sys/class/drm/card*/device | tail -n1)
	hmondir=$(find /sys/class/drm/card*/device/hwmon/hwmon* -type d | head -n1)
	echo "auto" >"$devdir"/power_dpm_force_performance_level
	echo "r" >"$devdir"/pp_od_clk_voltage
	echo "2" >"$hmondir"/pwm1_enable
	echo "c" >"$devdir"/pp_od_clk_voltage
else
	exit 1
fi
